version: 0.2

phases:
  pre_build:
    commands:
      - aws --version
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 111552573265.dkr.ecr.ap-south-1.amazonaws.com
    
  build:
    commands:
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - docker build -t ecs-deployment-repo .
      - docker tag ecs-deployment-repo:latest 111552573265.dkr.ecr.ap-south-1.amazonaws.com/ecs-deployment-repo:latest
  post_build:
    commands:
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - docker push 111552573265.dkr.ecr.ap-south-1.amazonaws.com/ecs-deployment-repo:latest
      - printf '[{"name":"farget-task-container","imageUri":"%s"}]' 111552573265.dkr.ecr.ap-south-1.amazonaws.com/ecs-deployment-repo:latest > imagedefinitions.json
artifacts:
  files: 
    - imagedefinitions.json
